version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  my-movie-list-front: ## nome do serviço
    build: . ## localização do dockerfile
    container_name: my-movie-list-front
    command: npm start ## comando a executar
    ports:
      - 3000:3000 ## redirecionamento de porta quando chegar alguma requisição na porta 3000 chama o container na porta 80
    volumes:
      - .:/usr/app ## monitoro a pasta atual . e envio as alterações para /usr/app

networks:
  default:
    name: webdev-network
    external: true